name: humini_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^1.1.1
  # المكتبات الأساسية وإدارة الحالة
  dio: ^5.4.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  clipboard: ^3.0.8
  cupertino_icons: ^1.0.8
  uuid: ^4.3.3
  animated_text_kit: ^4.2.2
  geolocator: ^13.0.1
  workmanager: ^0.5.2
  audioplayers: ^5.2.1
  
  # --- تم تحديث هذا السطر لإصدار أحدث وأكثر استقراراً ---
  flutter_notification_listener: 1.3.4 
  
  # الصوت والتنبيهات
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  
  # قواعد البيانات والملفات
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.1
  image: ^4.7.2

  # فايبربيز والذكاء الاصطناعي
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.4
  cloud_firestore: ^5.6.2
  google_sign_in: ^6.2.1
  google_generative_ai: ^0.4.7
  http: ^1.2.1
  flutter_markdown: ^0.7.7+1
  confetti: ^0.8.0
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/